#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
# Secrets policy: nothing is ever written to .env.local. Secrets live only in
# Vercel env vars; local steps borrow them per-command via `vercel env run`.
ENV_FILE="/dev/null"
PROD_URL="https://scanmana.vercel.app"
VENV="vercel env run -e production --"

# vercel_has NAME — true if NAME is set for production on the linked project.
vercel_has() { vercel env ls production 2>/dev/null | awk '{print $1}' | grep -qx "$1"; }

banner "Scanmana setup — Massive API key, backfill, first scan"

# ── Stage 1: create the API key ───────────────────────────────────────────
stage "Massive (formerly Polygon.io) — free API key"
say "Scanmana pulls EOD market data from Massive's free Basic tier (5 calls/min)."
note "The key is stored ONLY as a Vercel env var — never in .env.local."
if vercel_has MASSIVE_API_KEY; then
  say "✓ MASSIVE_API_KEY is already set on Vercel production."
  if ! confirm "Replace it with a new key?"; then
    NEW_KEY=""
  else
    ask_secret NEW_KEY "Paste the new API key:"
  fi
else
  open_url "https://massive.com/dashboard/signup"
  step "Sign up (or log in if you already have a Polygon.io account — same login)."
  step "In the dashboard, open 'API Keys' and copy your default key."
  ask_secret NEW_KEY "Paste the API key:"
fi
if [[ -n "${NEW_KEY:-}" ]]; then
  say "Adding it to Vercel production env..."
  if printf '%s' "$NEW_KEY" | vercel env add MASSIVE_API_KEY production --force >/dev/null 2>&1 \
    || printf '%s' "$NEW_KEY" | vercel env add MASSIVE_API_KEY production >/dev/null 2>&1; then
    WRITTEN_SECRET+=("MASSIVE_API_KEY (Vercel)")
    printf '  %s✓ set%s Vercel production env MASSIVE_API_KEY\n' "$GREEN" "$RESET"
  else
    warn "couldn't set the Vercel env var — run: printf '%s' \"<key>\" | vercel env add MASSIVE_API_KEY production"
    exit 1
  fi
  unset NEW_KEY
fi

# ── Stage 2: verify the key works ─────────────────────────────────────────
stage "Verify the key"
say "Fetching one day of grouped-daily data via Vercel's copy of the key..."
ok=""
for i in 1 2 3 4 5 6; do
  d=$(date -v-"${i}"d +%F 2>/dev/null || date -d "-${i} days" +%F)
  count=$($VENV sh -c "curl -sS \"https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/${d}?adjusted=true&apiKey=\$MASSIVE_API_KEY\"" \
    | python3 -c 'import json,sys; print(json.load(sys.stdin).get("resultsCount", 0))' 2>/dev/null || echo 0)
  if [[ "$count" -gt 1000 ]]; then ok="yes"; say "✓ ${d}: ${count} tickers returned — key works."; break; fi
  sleep 13   # free tier: 5 calls/min
done
if [[ -z "$ok" ]]; then
  warn "couldn't fetch data with that key — check it in the Massive dashboard, then re-run this wizard."
  exit 1
fi

# ── Stage 3: historical backfill ──────────────────────────────────────────
stage "Backfill one year of daily bars"
say "This makes ~250 API calls at the free-tier rate limit: roughly 55 minutes."
say "It's resume-safe — if it stops, re-run 'npm run backfill' and it continues."
note "Runs locally with secrets injected per-process from Vercel (npm run backfill)."
if confirm "Start the backfill now?"; then
  npm run backfill
  say "✓ backfill finished."
else
  SKIPPED+=("backfill (run: npm run backfill)")
  warn "skipped — the scan has nothing to chew on until you run: npm run backfill"
fi

# ── Stage 4: first scan ───────────────────────────────────────────────────
stage "Trigger the first scan"
say "Calling the production scan endpoint (takes a minute or two)..."
if $VENV bash scripts/scan-now.sh 1 2>/dev/null; then
  say "✓ if you see {\"status\":\"ok\",...} above, tonight's deck is live at:"
  say "  ${PROD_URL}"
else
  warn "CRON_SECRET isn't readable locally (it's marked Sensitive on Vercel), so trigger it from the dashboard:"
  open_url "https://vercel.com/dashboard"
  step "Open the project → Settings → Cron Jobs → /api/cron/scan → Run."
  step "Then open ${PROD_URL} — the deck should show tonight's setups."
  note "(The first scan of a day doesn't need force=1, so no secret is required.)"
  pause "Scan triggered?"
fi

# ── Stage 5: install on iPhone ────────────────────────────────────────────
stage "Install Scanmana on your iPhone"
step "On your iPhone, open ${PROD_URL} in Safari."
step "Tap Share → 'Add to Home Screen' → Add."
step "Open Scanmana from the home-screen icon (required for iOS push)."
step "Tap 'Enable nightly scan alerts' and allow notifications."
note "The nightly cron runs weekdays ~9:30pm ET; you'll get one push per scan."
pause "Done on the phone?"

finish
